name: 'project'
version: '1.0.0'
config-version: 2

profile: 'mi_proyecto_dbt'

model-paths: ["models"]

models:
  project:
    s1_staging:
      +materialized: table
    s2_intermediate:
      +materialized: view
    s3_marts:
      +materialized: table